### ISSUE TITLE
Uncaught TypeError: Cannot read property '0' of null

### ISSUE THREAD

**Issue by natl** [natl/language-geant4-macro#4]
Error occurs when a slash is placed in the string field for a command, as in a filename, as the provider tries to process it as a command

**Atom Version**: 1.8.0
**System**: Mac OS X 10.11.5
**Thrown From**: [language-geant4-macro](https://github.com/natl/language-geant4-macro) package, v1.1.0
### Stack Trace

Uncaught TypeError: Cannot read property '0' of null

```
At /..language-geant4-macro/lib/provider.coffee:57

TypeError: Cannot read property '0' of null
    at Object.module.exports.getCommandCompletions (/phdgits/language-geant4-macro/lib/provider.coffee:57:37)
    at Object.module.exports.getSuggestions (/phdgits/language-geant4-macro/lib/provider.coffee:14:22)
    at /Applications/Atom.app/Contents/Resources/app.asar/node_modules/autocomplete-plus/lib/autocomplete-manager.js:310:56
    at Array.forEach (native)
    at AutocompleteManager.module.exports.AutocompleteManager.getSuggestionsFromProviders (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/autocomplete-plus/lib/autocomplete-manager.js:289:17)
    at AutocompleteManager.getSuggestionsFromProviders (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/autocomplete-plus/lib/autocomplete-manager.js:3:61)
    at AutocompleteManager.module.exports.AutocompleteManager.findSuggestions (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/autocomplete-plus/lib/autocomplete-manager.js:276:19)
    at /Applications/Atom.app/Contents/Resources/app.asar/node_modules/autocomplete-plus/lib/autocomplete-manager.js:3:61
```
### Commands

```
```
### Config

``` json
{
  "core": {
    "allowPendingPaneItems": false,
    "themes": [
      "seti-ui",
      "one-dark-syntax"
    ]
  }
}
```
### Installed Packages

``` coffee
# User
Sublime-Style-Column-Selection, v1.5.1
autocomplete-python, v1.7.2
highlight-selected, v0.11.2
jquery-snippets, v11.0.0
jshint, v1.8.3
language-geant4-macro, v1.1.0
linter, v1.11.4
linter-bootlint, v1.0.2
linter-coffeelint, v1.1.2
linter-eslint, v7.2.1
linter-flake8, v1.13.0
linter-gcc, v0.6.12
minimap, v4.22.1
minimap-highlight-selected, v4.4.0
open-recent, v5.0.0
pigments, v0.26.0
seti-icons, v0.4.5
seti-ui, v0.9.2

# Dev
No dev packages
```

**Comment by natl** [comment]
The June 16 push fixed this

**Comment by natl** [comment]
Triggers error on typing

/gps./
